package com.paypal.stingray.http.server

import org.slf4j.LoggerFactory
import com.paypal.stingray.common.values.StaticValues

/**
 * Container for the information generated by a `status` endpoint request
 * @param status the status
 * @param serviceName the name
 * @param buildTag the build tag
 * @param dependencies the dependencies used
 */
case class StatusResponse(status: String,
                          serviceName: String,
                          buildTag: String,
                          dependencies: List[String])

object StatusResponse {

  private lazy val logger = LoggerFactory.getLogger(getClass)

  /**
   * Generate a StatusResponse based on current information
   * @param svs the StaticValues instance to read
   * @param serviceName the name
   * @return a StatusResponse object
   */
  def getStatusResponse(svs: StaticValues, serviceName: String): StatusResponse = {
    val partialStatus = svs.get("build.tag").map { buildTag =>
      StatusResponse("ok", serviceName, buildTag, _: List[String])
    }.getOrElse {
      StatusResponse("error", serviceName, "unknown", _: List[String])
    }
    val dependencies = svs.get("service.dependencies").map(_.split(",")).getOrElse(Array())
    val status = partialStatus(dependencies.toList)
    logger.debug(s"Status Response - status: ${status.status}, build tag: ${status.buildTag}, dependencies: ${dependencies.mkString(",")}")
    status
  }

}

