package com.paypal.stingray.http.server

import org.slf4j.LoggerFactory
import com.paypal.stingray.common.properties.BuildProperties

/**
 * Container for the information generated by a `status` endpoint request
 * @param status the status
 * @param serviceName the name
 * @param dependencies the dependencies used
 * @param gitInfo the repo info for this build
 */
case class StatusResponse(status: String,
                          serviceName: String,
                          dependencies: List[String],
                          gitInfo: List[String])

object StatusResponse {

  private lazy val logger = LoggerFactory.getLogger(getClass)

  /**
   * Generate a StatusResponse based on current information
   * @param props the BuildProperties instance to read
   * @param serviceName the name
   * @return a StatusResponse object
   */
  def getStatusResponse(props: BuildProperties, serviceName: String): StatusResponse = {
    val dependencies = props.get("service.dependencies").map(_.split(",")).getOrElse(Array())
    val gitInfo = List("git.branch", "git.branch.clean", "git.commit.sha", "git.commit.date").flatMap(props.get)
    val status = StatusResponse("ok", serviceName, dependencies.toList, gitInfo)
    logger.debug(s"Status Response - status: ${status.status}, dependencies: ${dependencies.mkString(",")}, Git Info: ${gitInfo.mkString(",")}")
    status
  }

}

